spring:
  application:
    name: employee-payroll-service
server:
  port: ${PORT:8201}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
     defaultZone: https://ms-eureka-server.herokuapp.com/eureka
  instance:
    securePortEnabled: true 
    securePort: ${PORT:8201}
    hostname: ${DOMAIN:localhost}
    homePageUrl: https://${eureka.instance.hostname}/
management:
  info:
    env:
      enabled: true